# Generated by Django 2.1.1 on 2019-01-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20190127_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='events',
            field=models.ManyToManyField(null=True, to='eventos.Event'),
        ),
    ]
