# Generated by Django 2.1.1 on 2019-01-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20190127_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='person',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='eventos.Person'),
            preserve_default=False,
        ),
    ]
