# Generated by Django 2.1.1 on 2019-01-29 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20190127_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
